{"tag": "function", "depth": 1, "time": 1697969052.8475718, "data": {"name": "connect_device", "call_args": {"uri": "android://127.0.0.1:5555/"}, "start_time": 1697969052.5805714, "traceback": "Traceback (most recent call last):\n  File \"H:\\SeeleAssistantCore\\venv\\Lib\\site-packages\\airtest\\utils\\logwraper.py\", line 131, in wrapper\n    res = f(*args, **kwargs)\n          ^^^^^^^^^^^^^^^^^^\n  File \"H:\\SeeleAssistantCore\\venv\\Lib\\site-packages\\airtest\\core\\api.py\", line 74, in connect_device\n    dev = init_device(platform, uuid, **params)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"H:\\SeeleAssistantCore\\venv\\Lib\\site-packages\\airtest\\core\\api.py\", line 42, in init_device\n    dev = cls(uuid, **kwargs)\n          ^^^^^^^^^^^^^^^^^^^\n  File \"H:\\SeeleAssistantCore\\venv\\Lib\\site-packages\\airtest\\core\\android\\android.py\", line 48, in __init__\n    self.serialno = serialno or self.get_default_device()\n                                ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"H:\\SeeleAssistantCore\\venv\\Lib\\site-packages\\airtest\\core\\android\\android.py\", line 254, in get_default_device\n    raise IndexError(\"ADB devices not found\")\nIndexError: ADB devices not found\n", "end_time": 1697969052.8475718}}
